// Generated by nul. Do not edit.
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

typedef struct { const char *ptr; int64_t len; } nul_str;

// A bump allocator, and the only thing the language needs at run time. A child
// borrows its parent's block, so releasing a parent releases every child with it.
typedef struct nul_arena nul_arena;
struct nul_arena {
    unsigned char *base;
    size_t size;
    size_t used;
    nul_arena *parent;
};

#define NUL_ARENA_SIZE (1u << 22)

nul_arena *nul_arena_init(void) {
    nul_arena *a = (nul_arena *)calloc(1, sizeof(nul_arena));
    a->base = (unsigned char *)malloc(NUL_ARENA_SIZE);
    a->size = NUL_ARENA_SIZE;
    return a;
}

nul_arena *nul_arena_child(nul_arena *parent) {
    nul_arena *a = nul_arena_init();
    a->parent = parent;
    return a;
}

void *nul_arena_alloc(nul_arena *a, size_t size) {
    size_t aligned = (a->used + 15u) & ~(size_t)15u;
    if (aligned + size > a->size) abort();
    a->used = aligned + size;
    return a->base + aligned;
}

void nul_arena_reset(nul_arena *a) { a->used = 0; }

void nul_arena_destroy(nul_arena *a) { free(a->base); free(a); }

nul_str nul_arena_copy_str(nul_arena *a, nul_str s) {
    char *bytes = (char *)nul_arena_alloc(a, (size_t)s.len + 1);
    memcpy(bytes, s.ptr, (size_t)s.len);
    bytes[s.len] = 0;
    return (nul_str){ bytes, s.len };
}


uint8_t keep(nul_arena * t0);

uint8_t keep(nul_arena * t0) {
    return 255;
}
